### ISSUE TITLE
Problem of detecting Chinese characters

### ISSUE THREAD

**Issue by sammo3182** [tidyverse/stringr#386] opened 2021-05-19 05:01 UTC
`str_detect`  looks not recognizing Chinese characters correctly. I'm using the 1.4.0.9000 dev version on R 4.1.0. Here's an example:

```r
Sys.setlocale(, locale = "Chinese")
library(string)
str_detect("昌平区", "县") # TRUE
grepl("县", "昌平区") # FALSE
```

```
> sessionInfo()
R Under development (unstable) (2021-05-17 r80314)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19042)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    
system code page: 65001

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] stringr_1.4.0.9000

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.6        pillar_1.6.1      compiler_4.2.0   
 [4] hrbrthemes_0.8.0  tools_4.2.0       extrafont_0.17   
 [7] digest_0.6.27     jsonlite_1.7.2    evaluate_0.14    
[10] lifecycle_1.0.0   tibble_3.1.2      gtable_0.3.0     
[13] pkgconfig_2.0.3   rlang_0.4.11      DBI_1.1.1        
[16] yaml_2.2.1        parallel_4.2.0    xfun_0.23        
[19] Rttf2pt1_1.3.8    dplyr_1.0.6       knitr_1.33       
[22] htmlwidgets_1.5.3 systemfonts_1.0.2 generics_0.1.0   
[25] gdtools_0.2.3     vctrs_0.3.8       grid_4.2.0       
[28] tidyselect_1.1.1  glue_1.4.2        R6_2.5.0         
[31] fansi_0.4.2       rmarkdown_2.8     mindr_1.2.3      
[34] ggplot2_3.3.3     purrr_0.3.4       extrafontdb_1.0  
[37] magrittr_2.0.1    scales_1.1.1      ellipsis_0.3.2   
[40] htmltools_0.5.1.1 assertthat_0.2.1  colorspace_2.0-1 
[43] utf8_1.2.1        stringi_1.6.2     munsell_0.5.0    
[46] crayon_1.4.1    
```

**Comment by gagolews** [comment] 2021-06-01 23:46
Could you try reproducing the above with `stringi` and, if still relevant, submit an issue at https://github.com/gagolews/stringi/ ?

**Comment by hadley** [comment] 2021-08-03 18:15
Closing since this seems to be at the stringi layer, not stringr.

**Closed by hadley** 2021-08-03 18:15 UTC
