### ISSUE TITLE
Issues with cyrillic letters

### ISSUE THREAD

**Issue by deann88** [tidyverse/stringr#344] opened 2020-07-22 11:27 UTC
I have had some issues with cyrillic letters and stringr package through the years. Here is one that I have recently stumbled upon. Any ideas how to fix that and still use stringr are highly appreciated.

```
# the code works fine with latin leters
> "I want to test that" %>% str_extract("(?<=want ).+(?=test)")
[1] "to "

# however, there seems to be an issue with cyrillic letters
> "I първо to второ that" %>% str_extract("(?<=първо ).+(?=второ)")
[1] NA
> enc2utf8("I първо to второ that") %>% str_extract("(?<=първо ).+(?=второ)")
[1] NA
```
Here is my sessionInfo()
```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.utf8        
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=bg_BG.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=bg_BG.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=bg_BG.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] glue_1.3.2      lubridate_1.7.4 forcats_0.5.0   stringr_1.4.0   readr_1.3.1    
 [6] tidyr_1.0.2     tibble_3.0.0    ggplot2_3.3.0   tidyverse_1.3.0 purrr_0.3.3    
[11] mongolite_2.2.0 quantmod_0.4.17 TTR_0.23-6      xts_0.12-0      zoo_1.8-7      
[16] dplyr_1.0.0    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4       cellranger_1.1.0 pillar_1.4.3     compiler_3.6.3   dbplyr_1.4.2    
 [6] tools_3.6.3      jsonlite_1.6.1   lifecycle_0.2.0  nlme_3.1-145     gtable_0.3.0    
[11] lattice_0.20-40  pkgconfig_2.0.3  rlang_0.4.6      reprex_0.3.0     cli_2.0.2       
[16] DBI_1.1.0        rstudioapi_0.11  curl_4.3         yaml_2.2.1       haven_2.2.0     
[21] withr_2.1.2      xml2_1.2.5       httr_1.4.1       fs_1.4.0         hms_0.5.3       
[26] generics_0.0.2   vctrs_0.3.1      grid_3.6.3       tidyselect_1.1.0 R6_2.4.1        
[31] fansi_0.4.1      readxl_1.3.1     modelr_0.1.6     magrittr_1.5     scales_1.1.0    
[36] backports_1.1.5  ellipsis_0.3.0   rvest_0.3.5      assertthat_0.2.1 colorspace_1.4-1
[41] utf8_1.1.4       stringi_1.4.6    munsell_0.5.0    broom_0.5.5      crayon_1.3.4 
```

**Comment by gagolews** [comment] 2020-07-23 06:07
Most likely a duplicate of https://github.com/gagolews/stringi/issues/147

This is an old bug in ICU that has been fixed some time ago. Apparently, you're still using an older version. Either upgrade `libicu` on your system or compile stringi without the system ICU, e.g., via `install.packages("stringi", configure.args="--disable-pkg-config")`. HTH.

**Comment by deann88** [comment] 2020-07-23 09:06
libicu-dev was latest version on my ubuntu 16.04, however, installing `stringi` the way you described did the job for me. Thanks.

**Closed** 2020-07-23 09:07 UTC
