### ISSUE TITLE
Add str_to_capitalised()

### ISSUE THREAD

**Issue by foldager** [tidyverse/stringr#231] opened 2018-03-29 17:33 UTC
Complement `str_to_lower()`, `str_to_upper()` and `str_to_title` with a function for capitalising the first word in each sentence. The only problem is that stringi does not see a dot followed by a lower case letter as a sentence break. That should probably be documented, or it will lead to confusion. It would still be a useful function for me though.

    > stri_trans_totitle("it works. but not always. now? yes! indeed; but not with dot. lowercase.", stri_opts_brkiter('sentence'))
    [1] "It works. but not always. now? Yes! Indeed; but not with dot. lowercase."

From [stringi](https://cran.r-project.org/web/packages/stringi/stringi.pdf)

> With stri_trans_totitle, if word BreakIterator is used (the default), then the first letter of each word will be capitalized and the rest will be transformed to lower case. With a break iterator of type sentence, the first letter of each sentence will be capitalized only. Note that according the ICU User Guide, the string "one. two. three." consists of one sentence.

[Unicode sentence bounderies](http://www.unicode.org/reports/tr29/#Sentence_Boundaries) 

Relevant issue: #27

**Comment by hadley** [comment] 2018-05-08 17:35
I don't really understand what you are asking for here. Can you please clarify?

**Comment by hadley** [comment] 2018-05-08 17:40
Is this a duplicate of #202?

**Comment by foldager** [comment] 2018-05-08 17:42
Yes, it is a dup. I wanted a function to convert lowercase text to sentence case. However, stringi does not see a full-stop followed by a lower case letter as a sentence boundary.

**Closed** 2018-05-08 19:00 UTC
